"""Compare replay outputs with separately saved pre-bundle audit results."""
from pathlib import Path
import argparse, json, re
import numpy as np
import pandas as pd

P=Path(__file__).resolve().parents[1]
ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--results',type=Path,default=P/'results')
args=ap.parse_args();R=args.results;E=P/'expected';checks=[]
def csv_check(actual,expected):
    a=pd.read_csv(actual);b=pd.read_csv(expected)
    pd.testing.assert_frame_equal(a,b,check_dtype=False,check_exact=False,rtol=1e-10,atol=1e-11)
    checks.append({'file':actual.relative_to(R).as_posix(),'rows':len(a),'status':'numeric/text match'})
for name in ['corrected_AllComposite.csv','corrected_TopFamilies.csv','score_migrations.csv','tier_migrations.csv','ubiquitous_controls.csv','control_migrations_vs169.csv']:
    csv_check(R/'current167'/name,E/name)
for expected in sorted((E/'figures').glob('*.csv')):csv_check(R/'figures'/expected.name,expected)
for expected in sorted(E.glob('*_rank_stability.csv')):csv_check(R/'rank_sensitivity'/expected.name,expected)
a=pd.read_json(R/'reconstruction/score_family_reconstruction.json');b=pd.read_json(E/'score_family_reconstruction.json')
pd.testing.assert_frame_equal(a,b,check_dtype=False,check_exact=False,rtol=1e-10,atol=1e-10)
checks.append({'file':'reconstruction/score_family_reconstruction.json','rows':len(a),'status':'independent raw-input reconstruction matches pre-bundle reconstruction'})
def same(a,b,path=''):
    if isinstance(a,dict):
        assert a.keys()==b.keys(),path
        for k in a:same(a[k],b[k],path+'/'+k)
    elif isinstance(a,list):
        assert len(a)==len(b),path
        for i,(x,y) in enumerate(zip(a,b)):same(x,y,path+'/'+str(i))
    elif isinstance(a,(int,float)) and not isinstance(a,bool):assert np.isclose(a,b,rtol=1e-10,atol=1e-11,equal_nan=True),path
    else:assert a==b,(path,a,b)
mapping=json.loads((R/'mapping_sensitivity/summary.json').read_text())
same(mapping['sensitivities'],json.loads((E/'mapping_sensitivities.json').read_text()))
assert mapping['original_files_unchanged']
checks.append({'file':'mapping_sensitivity/summary.json','status':'all sensitivity counts, scores and migrations match pre-bundle audit'})
# Original independent stdout includes every fitted OR, interval, P value and
# sample/stratum count. Compare numeric tokens, permitting display roundoff.
num=r'(?<![A-Za-z_])[-+]?(?:\d+\.\d*|\.\d+|\d+)(?:[eE][-+]?\d+)?'
original=(E/'original_independent_regression_stdout.txt').read_text(encoding='utf-8-sig')
current=(R/'logs/04_independent_regressions.txt').read_text(encoding='utf8').split('\nSTDERR:')[0]
aa=[float(x) for x in re.findall(num,current)];bb=[float(x) for x in re.findall(num,original)]
assert len(aa)==len(bb),(len(aa),len(bb))
np.testing.assert_allclose(aa,bb,rtol=1e-9,atol=1e-10)
checks.append({'file':'diagnostics/independent_regressions.json','status':'all independent regression output numerical tokens match original audit','numeric_tokens':len(aa)})
old=(E/'original_historical_diagnostics.txt').read_text(encoding='utf-8-sig')
new=(R/'logs/03_historical_diagnostics.txt').read_text(encoding='utf8').split('\nSTDERR:')[0]
# These stable lines span D1-D8. Changed editorial headings are not scientific
# evidence; the portable script deliberately qualifies the original wording.
markers=["Model-Supported 'Other / unassigned':",'specific named function :','generic / hypothetical  :','truly generic/hypothetical names',
 'central carbon-metabolism enzymes by product name:','of which binned','sulfur-metabolism enzymes filed',
 '  model_score ','  morphotype_breadth_score ','  literature_proteomics_score ','  related_atlas_score ','  condensate_score ',
 'ZERO external evidence:','Tier A families passing both','Spearman(model','median model rank pct:',
 'logit up ~','Model-Supported OR,','carrier-genome prevalence OR','median carrier genomes:',
 'carriers: MS','detected in','  Tier A:','within-minus-between r']
def selected_numbers(text):
    lines=[line for line in text.splitlines() if any(marker in line for marker in markers)]
    return lines,[float(x) for line in lines for x in re.findall(num,line)]
ll,nn=selected_numbers(new);ol,on=selected_numbers(old)
assert len(ll)==len(ol),(ll,ol)
np.testing.assert_allclose(nn,on,rtol=1e-9,atol=1e-10)
checks.append({'file':'logs/03_historical_diagnostics.txt','status':'historical D1-D8 numerical result lines match original audit','lines':len(ll),'numeric_tokens':len(nn)})
summary=json.loads((R/'current167/score_revision_summary.json').read_text())
assert summary['corrected']['shortlist_count']==167 and summary['corrected']['activeup_shortlist']==65
assert summary['original_workbook_unchanged']
report={'status':'PASS','reference_scope':'Expected files were captured from completed audits before constructing this package; no expected values are regenerated by run_all.py.','checks':checks}
(R/'verification.json').write_text(json.dumps(report,indent=2),encoding='utf8')
print(json.dumps(report,indent=2))
